# Generated by Django 4.2.7 on 2023-11-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('someapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='empname',
            field=models.CharField(default='ramesh', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='empsal',
            field=models.IntegerField(null=True),
        ),
    ]
