# Generated by Django 4.2.7 on 2023-11-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('someapp', '0002_employee_empname_employee_empsal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='empno',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='empsal',
            field=models.IntegerField(default=0),
        ),
    ]
